In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
boston=pd.read_csv("BostonHousing.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
boston.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         5
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [4]:
boston['rm']=boston['rm'].fillna(boston['rm'].mean())

In [5]:
boston.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [6]:
df=pd.DataFrame(boston)

In [7]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [8]:
df.columns=boston.columns

In [9]:
df['price']=boston['medv']

In [10]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9,11.9

In [11]:
df=df.drop('medv',axis=1)

In [12]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [13]:
x=boston

In [14]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [15]:
x=x.drop('medv',axis=1)

In [16]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [17]:
y=boston['medv']

In [18]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=31)

In [22]:
import tensorflow

In [23]:
from tensorflow.keras import Sequential
from keras.layers import Dense

In [24]:
model=Sequential()

In [25]:
model.add(Dense(80,activation='relu',input_dim=13))

c:\Users\harsh\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [26]:
model.add(Dense(40,activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='linear'))

In [27]:
model.compile(optimizer='adam',loss='mean_squared_error')

In [28]:
model.fit(xtrain,ytrain,epochs=100,batch_size=20,validation_data=(xtest,ytest))

Epoch 1/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - loss: 609.7233 - val_loss: 525.6489
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 589.8859 - val_loss: 524.7632
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 573.5798 - val_loss: 523.8832
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 574.8643 - val_loss: 522.9980
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 639.5583 - val_loss: 522.1036
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 629.8624 - val_loss: 521.2255
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 657.0889 - val_loss: 520.3500
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 551.6524 - val_loss: 519.4824
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 578.2600 - val_loss: 518.5986
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 611.3854 - val_loss: 517.7112
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 630.7224 - val_loss: 516.8371
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 607.2277 - val_loss: 515.9648
Epoch 13/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 637.2867 - val_loss: 515.0791
Epoch 14/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 623.2679 - val_loss: 514.2091
Epoch 15/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 599.2008 - val_loss: 513.3466
Epoch 16/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 635.0054 - val_loss: 512.4800
Epoch 17/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 542.2265 - val_loss: 511.6173
Epoch 18/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 551.4304 - val_loss: 510.7311
Epoch 19/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 581.8901 - val_loss: 509.8608
Epoch 20/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 570.5753 - val_loss: 508.9900
Epoch 21/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 564.0701 - val_loss: 508.1327
Epoch 22/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 617.1905 - val_loss: 507.2686
Epoch 23/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 546.6801 - val_loss: 506.4207
Epoch 24/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 556.7860 - val_loss: 505.5666
Epoch 25/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 589.7162 - val_loss: 504.7069
Epoch 26/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 582.0809 - val_loss: 503.8586
Epoch 27/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 613.4997 - val_loss: 503.0111
Epoch 28/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 611.6243 - val_loss: 502.1546
Epoch 29/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 556.6537 - val_loss: 501.3107
Epoch 30/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 599.7408 - val_loss: 500.4523
Epoch 31/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 591.2897 - val_loss: 499.6039
Epoch 32/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 575.1414 - val_loss: 498.7505
Epoch 33/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 605.1411 - val_loss: 497.8894
Epoch 34/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 599.5162 - val_loss: 497.0481
Epoch 35/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 572.9629 - val_loss: 496.2050
Epoch 36/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 589.4827 - val_loss: 495.3477
Epoch 37/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 549.4866 - val_loss: 494.5143
Epoch 38/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 571.3286 - val_loss: 493.6760
Epoch 39/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 564.9595 - val_loss: 492.8441
Epoch 40/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 573.5200 - val_loss: 492.0055
Epoch 41/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 586.7764 - val_loss: 491.1637
Epoch 42/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 585.2861 - val_loss: 490.3310
Epoch 43/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 581.3184 - val_loss: 489.5052
Epoch 44/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 551.9965 - val_loss: 488.6827
Epoch 45/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 569.3788 - val_loss: 487.8497
Epoch 46/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 551.3589 - val_loss: 487.0222
Epoch 47/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 570.9338 - val_loss: 486.1772
Epoch 48/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 556.3061 - val_loss: 485.3366
Epoch 49/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 593.8384 - val_loss: 484.5135
Epoch 50/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 586.4115 - val_loss: 483.6898
Epoch 51/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 543.0391 - val_loss: 482.8723
Epoch 52/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 587.2294 - val_loss: 482.0372
Epoch 53/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 566.1091 - val_loss: 481.2169
Epoch 54/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 574.6576 - val_loss: 480.3928
Epoch 55/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 543.3707 - val_loss: 479.5707
Epoch 56/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 560.8533 - val_loss: 478.7545
Epoch 57/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 552.8945 - val_loss: 477.9439
Epoch 58/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 548.8065 - val_loss: 477.1327
Epoch 59/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 550.5938 - val_loss: 476.3159
Epoch 60/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 554.6412 - val_loss: 475.4877
Epoch 61/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 523.5966 - val_loss: 474.6750
Epoch 62/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 555.0107 - val_loss: 473.8595
Epoch 63/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 535.8281 - val_loss: 473.0559
Epoch 64/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 534.1660 - val_loss: 472.2513
Epoch 65/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 569.5834 - val_loss: 471.4231
Epoch 66/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 538.2892 - val_loss: 470.6181
Epoch 67/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 543.6959 - val_loss: 469.8160
Epoch 68/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 541.7593 - val_loss: 469.0080
Epoch 69/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 570.9979 - val_loss: 468.2084
Epoch 70/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 557.4369 - val_loss: 467.4007
Epoch 71/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 544.2595 - val_loss: 466.5998
Epoch 72/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 508.9542 - val_loss: 465.8076
Epoch 73/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 535.2738 - val_loss: 465.0016
Epoch 74/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 553.1486 - val_loss: 464.1967
Epoch 75/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 522.6324 - val_loss: 463.3883
Epoch 76/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 531.5560 - val_loss: 462.5850
Epoch 77/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 571.0090 - val_loss: 461.7930
Epoch 78/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 577.0967 - val_loss: 460.9925
Epoch 79/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 567.6035 - val_loss: 460.2066
Epoch 80/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 524.5115 - val_loss: 459.4046
Epoch 81/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 542.1733 - val_loss: 458.6124
Epoch 82/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 527.9415 - val_loss: 457.8174
Epoch 83/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 533.4263 - val_loss: 457.0242
Epoch 84/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 480.4637 - val_loss: 456.2446
Epoch 85/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 557.3011 - val_loss: 455.4344
Epoch 86/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 570.4957 - val_loss: 454.6400
Epoch 87/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 534.3587 - val_loss: 453.8607
Epoch 88/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 505.1769 - val_loss: 453.0767
Epoch 89/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 535.6797 - val_loss: 452.2733
Epoch 90/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 481.6789 - val_loss: 451.4979
Epoch 91/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 515.5890 - val_loss: 450.7186
Epoch 92/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 518.2751 - val_loss: 449.9303
Epoch 93/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 512.4327 - val_loss: 449.1452
Epoch 94/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 524.5913 - val_loss: 448.3629
Epoch 95/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 508.1577 - val_loss: 447.5872
Epoch 96/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 513.4692 - val_loss: 446.8112
Epoch 97/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 484.3558 - val_loss: 446.0357
Epoch 98/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 506.5357 - val_loss: 445.2531
Epoch 99/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 510.7133 - val_loss: 444.4619
Epoch 100/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 511.8878 - val_loss: 443.6966

In [29]:
loss=model.evaluate(xtest,ytest)
loss

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 432.6833

443.6966247558594